services:
  app:
    build: .
    container_name: swaratani_app
    restart: always
    environment:
      # App
      APP_NAME: Swaratani
      APP_ENV: production
      APP_KEY: base64:HtrUI7eICD5Y+1mLCivZceVUs4uEMLe2YY+ToZiFZGM=
      APP_DEBUG: "false"
      APP_URL: https://swaratani.id
      # Database (server terpisah)
      DB_CONNECTION: pgsql
      DB_HOST: 76.13.21.232
      DB_PORT: 5432
      DB_DATABASE: db_swaratani
      DB_USERNAME: webadmin
      DB_PASSWORD: "IF#RwhhmD2#EA6"
      # Session & Cache
      SESSION_DRIVER: file
      CACHE_STORE: file
      QUEUE_CONNECTION: sync
      LOG_CHANNEL: stack
      FILESYSTEM_DISK: local
      # MQTT
      MQTT_HOST: 76.13.21.230
      MQTT_PORT: 1883
      MQTT_USERNAME: iot
      MQTT_PASSWORD: smartgh
      MQTT_TOPIC_PUB: /smartgh01/pub
      MQTT_TOPIC_SUB: /smartgh01/sub
      # Mail (Resend)
      MAIL_MAILER: resend
      MAIL_FROM_ADDRESS: "noreply@swaratani.id"
      MAIL_FROM_NAME: "Swaratani IoT"
      RESEND_API_KEY: re_Bnoui28A_EF8KvLGbF6JKk65v3L4QbgvM
    volumes:
      - ./src/storage:/var/www/html/storage
    networks:
      - webapps

networks:
  webapps:
    external: true
